version: '2'
services:
  finder:
    build: .
    image: mantiser/finder
    volumes:
      - ./:/code
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
      RESULT_NATS: nats
      REDIS: redis
    #command: tail -f /etc/fstab
    networks:
      - mantiser
networks:
  mantiser:
    external: true