version: '2'
services:
  finder:
    build: .
    image: mantiser/finder
    volumes:
      - ./:/code
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
      RESULT_NATS: nats
      REDIS: redis
    #command: tail -f /etc/fstab
    depends_on: 
      - nats
    links:
      - "nats"
      - "splash"
      - "meilisearch"
      - "redis"
  nats:
    image: nats
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
  redis:
    image: redis