version: '2'
services:
  finder-email:
    build: .
    volumes:
      - ./:/code
    environment:
      SEARCH: "mantier"
      NATS: nats
      USER_ID: "ahsdjkhasjkdhajksdhajkshdk"
      RESULT_NATS: nats
    command: tail -f /etc/fstab
    depends_on: 
      - nats
  nats:
    image: nats
