---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mantiser-com/user_id: "1112"
  name: finder-email
  labels:
    app: finder-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finder-email
  template:
    metadata:
      annotations:
        app: finder-email
      labels:
        app: finder-email
    spec:
      volumes:
        - name: files-disk
          persistentVolumeClaim:
            claimName: files-disk
      containers:
        - name: splash
          image: scrapinghub/splash:master
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8050
            name: splash
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
        - name: search
          volumeMounts:
            - name: files-disk
              mountPath: /files
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: REDISHOST
              value: redis
            - name: REDIS
              value: redis
            - name: REDISPORT
              value: "6379"
            - name: AUTH_TOKENS
              value: "['1234','6789']"
            - name: ELASTICSEARCH
              value: http://elasticsearch:9200
            - name: ES_INDEX
              value: mantiser
            - name: INDB
              value: influxdb
            - name: INDB_PORT
              value: "8086"
            - name: INDB_USER
              value: influxdb
            - name: INDB_PASSWORD
              value: influxdb
            - name: INDB_DATABASE
              value: ollebo
            - name: INDB_TOKEN
              value: aaaaaaaaa
            - name: INDB_ORG
              value: mantiser
            - name:  MEILISEARCH
              value: http://meilisearch:7700
            - name: PROJECT
              value: mantiser
            - name: MONGOURL
              value: urlsiiii
            - name: SPLASH
              value: http://localhost:8050/render.html
          resources:
            requests:
              cpu: 100m
              memory: 256Mi



            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mantiser-com/user_id: "1112"
  name: finder-people
  labels:
    app: finder-people
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finder-people
  template:
    metadata:
      annotations:
        app: finder-people
      labels:
        app: finder-people
    spec:
      containers:
        - name: splash
          image: scrapinghub/splash:master
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8050
            name: splash
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
        - name: people
          command: ["python","startPeople.py"]
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: REDISHOST
              value: redis
            - name: REDIS
              value: redis
            - name: REDISPORT
              value: "6379"
            - name: AUTH_TOKENS
              value: "['1234','6789']"
            - name: ELASTICSEARCH
              value: http://elasticsearch:9200
            - name: ES_INDEX
              value: mantiser
            - name: INDB
              value: influxdb
            - name: INDB_PORT
              value: "8086"
            - name: INDB_USER
              value: influxdb
            - name: INDB_PASSWORD
              value: influxdb
            - name: INDB_DATABASE
              value: ollebo
            - name: INDB_TOKEN
              value: aaaaaaaaa
            - name: INDB_ORG
              value: mantiser
            - name:  MEILISEARCH
              value: http://meilisearch:7700
            - name: PROJECT
              value: mantiser
            - name: MONGOURL
              value: urlsiiii
            - name: SPLASH
              value: http://splash:8050/render.html
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mantiser-com/user_id: "1112"
  name: finder-company
  labels:
    app: finder-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finder-company
  template:
    metadata:
      annotations:
        app: finder-company
      labels:
        app: finder-company
    spec:
      initContainers:
        - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          name: db-init
          imagePullPolicy: Always
          command: ["python3",","initnats.py"]
          env:
            - name: NATS
              value: nats
      containers:
        - name: splash
          image: scrapinghub/splash:master
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8050
            name: splash
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8050
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
        - name: company
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          command: ["python","startCompany.py"]
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: REDISHOST
              value: redis
            - name: REDIS
              value: redis
            - name: REDISPORT
              value: "6379"
            - name: AUTH_TOKENS
              value: "['1234','6789']"
            - name: ELASTICSEARCH
              value: http://elasticsearch:9200
            - name: ES_INDEX
              value: mantiser
            - name: INDB
              value: influxdb
            - name: INDB_PORT
              value: "8086"
            - name: INDB_USER
              value: influxdb
            - name: INDB_PASSWORD
              value: influxdb
            - name: INDB_DATABASE
              value: ollebo
            - name: INDB_TOKEN
              value: aaaaaaaaa
            - name: INDB_ORG
              value: mantiser
            - name:  MEILISEARCH
              value: http://meilisearch:7700
            - name: PROJECT
              value: mantiser
            - name: MONGOURL
              value: urlsiiii
            - name: SPLASH
              value: http://splash:8050/render.html
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
